### ISSUE TITLE
[BUG] WTFTool's is causing a crash

### ISSUE THREAD

**Issue by GazbonicAcid** [WhiskyTangoFawks/WTFTools#2]
WTFTools is making the game crash when their inventory model is viewed.
Unfortunately since this happens instantly upon the item appearing on-screen I am physically incapable of telling you which item(s) it is.
Also, none of the ones I was able to view in vanilla creative inventory had their models/textures.
[http://paste.atlauncher.com/view/91c7aa53](http://paste.atlauncher.com/view/91c7aa53)
[Logs.zip](https://github.com/WhiskyTangoFawks/WTFTools/files/907920/Logs.zip)

**Comment by WhiskyTangoFawks** [comment]
Did you have a tool made on Alpha 2, then upgrade to alpha 3?

**Comment by GazbonicAcid** [comment]
No.
This is on the latest version of the time I opened this issue.
And I haven't made any tools either.

**Comment by WhiskyTangoFawks** [comment]
Hmmm, weird.  Well, either way, this crash should be resolved in the new alpha.

**Comment by GazbonicAcid** [comment]
yeah it is.
The model generation's still not working though.
All stuff is a black and pink null block viewed in-world,
tool parts are black and pink squares that fill up their inventory "slot".
Only difference between the tool parts, and finished tools visually speaking.
Is that the inventory icon for tools is a smaller rectange centered horizontily with a gap between the left/right/top of the icon and the right/left/top of the inventory "slot"...plus the damage bar.

**Comment by WhiskyTangoFawks** [comment]
Are you by any chance running foamfix or anything else that might alter model loading?  I've tested it with optifine, and that has no issues.

**Comment by GazbonicAcid** [comment]
I had steadfastly stuck with the believe it would generate the resource pack in the same folder as the config.
I'll check the actual resourcepack folder now.

**Comment by GazbonicAcid** [comment]
Is it _supposed_ to generate it as a folder/file structure inside the resourcepack folder?

**Comment by WhiskyTangoFawks** [comment]
Yes, it's supposed to generate a resourcepack in the standard resource pack folder, and should load like any other resource pack.  It doesn't currently auto-enable itself unless you have the WTF-expedition mod installed also.

If it isn't generating at all, then it may be an issue with your minecraft installation being unusual.  I've had reports of issues with the file writer not getting the correct default path from users with a non-default launcher, or who had installed minecraft somewhere unusual.

**Comment by GazbonicAcid** [comment]
clearly you missed the meaning between the lines.
It generated as a folder/file structure.
>.>

**Comment by WhiskyTangoFawks** [comment]
Folder structures are resource packs.  It doesn't matter whether it's zipped or not, minecraft can still read it just fine.  Load it, and that should solve your missing model issues.
